// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsfOZFfxAAqNSsVRe792qErZzPrVI3IwY',
    appId: '1:524873281827:web:5193baaba02568202ddc96',
    messagingSenderId: '524873281827',
    projectId: 'test-login-d391a',
    authDomain: 'test-login-d391a.firebaseapp.com',
    storageBucket: 'test-login-d391a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5Ulh1DsoSHVmN08ytXQeKQocLJkj_1P0',
    appId: '1:524873281827:android:badcbe26182c4d082ddc96',
    messagingSenderId: '524873281827',
    projectId: 'test-login-d391a',
    storageBucket: 'test-login-d391a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRu2hWUwfCdid6EfnSsMM4yYYW_zFqjp8',
    appId: '1:524873281827:ios:b8d74dca67c9b2332ddc96',
    messagingSenderId: '524873281827',
    projectId: 'test-login-d391a',
    storageBucket: 'test-login-d391a.firebasestorage.app',
    iosBundleId: 'com.example.testLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRu2hWUwfCdid6EfnSsMM4yYYW_zFqjp8',
    appId: '1:524873281827:ios:b8d74dca67c9b2332ddc96',
    messagingSenderId: '524873281827',
    projectId: 'test-login-d391a',
    storageBucket: 'test-login-d391a.firebasestorage.app',
    iosBundleId: 'com.example.testLogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsfOZFfxAAqNSsVRe792qErZzPrVI3IwY',
    appId: '1:524873281827:web:a36cd5eed9e196712ddc96',
    messagingSenderId: '524873281827',
    projectId: 'test-login-d391a',
    authDomain: 'test-login-d391a.firebaseapp.com',
    storageBucket: 'test-login-d391a.firebasestorage.app',
  );
}
